FROM docker.io/openresty/openresty:alpine

RUN apk update && \
    apk upgrade && \
    apk add curl openssl tar

RUN curl -LO https://github.com/ledgetech/lua-resty-http/archive/refs/tags/v0.17.0-beta.1.tar.gz && \
    tar -xvzf v0.17.0-beta.1.tar.gz && \
    mv lua-resty-http-0.17.0-beta.1 /etc/lua-resty-http && \
    rm -rf v0.17.0-beta.1.tar.gz

RUN curl -LO https://github.com/fffonion/lua-resty-openssl/archive/refs/tags/0.8.5.tar.gz && \
    tar -xvzf 0.8.5.tar.gz && \
    mv lua-resty-openssl-0.8.5 /etc/lua-resty-openssl && \
    rm -rf 0.8.5.tar.gz

RUN curl -LO https://github.com/jkeys089/lua-resty-hmac/archive/refs/tags/v0.06.tar.gz && \
    tar -xvzf v0.06.tar.gz && \
    mv lua-resty-hmac-0.06 /etc/lua-resty-hmac && \
    rm -rf v0.06.tar.gz

RUN curl -LO https://github.com/cdbattags/lua-resty-jwt/archive/refs/tags/v0.2.3.tar.gz && \
    tar -xvzf v0.2.3.tar.gz && \
    mv lua-resty-jwt-0.2.3 /etc/lua-resty-jwt && \
    rm -rf v0.2.3.tar.gz

RUN apk del curl tar
