services:
    envoy:
        container_name: filebrowser-envoy
        image: docker.io/envoyproxy/envoy-alpine:v1.21-latest
        restart: always
        volumes:
            - ./volume/envoy:/etc/envoy:ro
        security_opt:
            label: disable
        depends_on: 
            - filebrowser
        command: /usr/local/bin/envoy --log-level debug -c /etc/envoy/envoy.yaml

    mongo:
        container_name: filebrowser-mongo
        image: docker.io/mongo:latest
        restart: always
        volumes:
            - dbdata:/data/db
        security_opt:
            label: disable
        env_file:
            - .env

    filebrowser:
        container_name: filebrowser-server
        image: docker.io/alvidir/filebrowser:0.1.0
        restart: always
        security_opt:
            label: disable
        depends_on: 
            - mongo
        env_file:
            - .env

    mqworker:
        container_name: filebrowser-mqworker
        image: docker.io/alvidir/filebrowser:0.1.0-mqworker
        restart: always
        security_opt:
            label: disable
        networks:
            - shared
        env_file:
            - .env

networks:
    shared:
        external: true

volumes:
    dbdata: