services:
    envoy:
        container_name: filebrowser-envoy
        image: docker.io/envoyproxy/envoy-alpine:v1.21.6
        restart: always
        volumes:
            - ./volume/envoy:/etc/envoy:ro
        security_opt:
            label: disable
        depends_on: 
            - filebrowser
        command: /usr/local/bin/envoy --log-level debug -c /etc/envoy/envoy.yaml

    nginx:
        container_name: filebrowser-nginx
        build: ./container/nginx
        restart: always
        volumes:
            - ./volume/nginx:/opt/bitnami/openresty/nginx/conf/server_blocks:ro
        security_opt:
            label: disable
        depends_on:
            - envoy
        networks:
            - shared
        env_file:
            - .env

    mongo:
        container_name: filebrowser-mongo
        image: docker.io/mongo:6.0.3
        restart: always
        volumes:
            - dbdata:/data/db
        security_opt:
            label: disable
        env_file:
            - .env

    filebrowser:
        container_name: filebrowser-server
        image: docker.io/alvidir/filebrowser:0.0.6
        restart: always
        security_opt:
            label: disable
        depends_on: 
            - mongo
        env_file:
            - .env

    filebrowser-ui:
        container_name: filebrowser-ui
        image: docker.io/alvidir/filebrowser-ui:0.0.7
        restart: always
        security_opt:
            label: disable
        env_file:
            - .env

    agent:
        container_name: filebrowser-agent
        image: docker.io/alvidir/filebrowser:0.0.6-agent
        restart: always
        security_opt:
            label: disable
        depends_on:
            - rabbitmq
        env_file:
            - .env

networks:
    shared:
        external: true

volumes:
    dbdata:
