services:
    envoy:
        container_name: filebrowser-envoy
        build:
            context: ../envoy
            dockerfile: ./container/envoy/containerfile
        restart: always
        volumes:
            - ./volume/envoy:/etc/envoy/.config:ro
        security_opt:
            label: disable
        env_file:
            - .env

    nginx:
        container_name: filebrowser-nginx
        image: docker.io/nginx:1.23.2-alpine
        restart: always
        volumes:
            - ./volume/nginx:/etc/nginx/conf.d:ro
        security_opt:
            label: disable
        depends_on:
            - envoy
        networks:
            - shared
        env_file:
            - .env

    mongo:
        container_name: filebrowser-mongo
        image: docker.io/mongo:6.0.3
        restart: always
        volumes:
            - dbdata:/data/db
        security_opt:
            label: disable
        env_file:
            - .env

    grpc:
        container_name: filebrowser-grpc
        image: docker.io/alvidir/filebrowser:v0.0.10-grpc
        restart: always
        security_opt:
            label: disable
        depends_on: 
            - mongo
        env_file:
            - .env
        environment:
            - SERVICE_PORT=${GRPC_SERVICE_PORT}

    rest:
        container_name: filebrowser-rest
        image: docker.io/alvidir/filebrowser:v0.0.10-rest
        restart: always
        security_opt:
            label: disable
        depends_on: 
            - mongo
        env_file:
            - .env
        environment:
            - SERVICE_PORT=${REST_SERVICE_PORT}

    agent:
        container_name: filebrowser-agent
        image: docker.io/alvidir/filebrowser:v0.0.10-agent
        restart: always
        security_opt:
            label: disable
        depends_on:
            - rabbitmq
        env_file:
            - .env

    ui:
        container_name: filebrowser-ui
        image: docker.io/alvidir/filebrowser-ui:0.0.9
        restart: always
        security_opt:
            label: disable
        env_file:
            - .env

networks:
    shared:
        external: true

volumes:
    dbdata:
