services:
    rabbitmq:
        container_name: rabbitmq
        image: docker.io/rabbitmq:3.11.3-alpine
        hostname: rabbitmq
        restart: always
        security_opt:
            label: disable
        networks:
            - shared

networks:
    shared:
        external: true