services:
    nginx:
        container_name: ingress
        build: ./container/nginx
        restart: always
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./volume/nginx:/opt/bitnami/openresty/nginx/conf/server_blocks:ro
            - ./volume/lua:/etc/lua:ro
        security_opt:
            label: disable
        networks:
            - shared
        env_file:
            - .env

networks:
    shared:
        external: true
