services:
    nginx:
        container_name: global-nginx
        image: localhost/alvidir/nginx-lua:1.0.0
        restart: always
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./volume/nginx:/etc/nginx/conf.d:ro
            - ./volume/lua:/etc/lua:ro
        security_opt:
            label: disable
        networks:
            - shared
        env_file:
            - .env

networks:
    shared:
        external: true
