services:
    redis:
        container_name: webcache-redis
        image: docker.io/redis:alpine3.15
        restart: always
        volumes:
            - ./volume/redis:/usr/local/etc/redis:ro
        security_opt:
            label: disable
        command: "redis-server /usr/local/etc/redis/redis.conf"

    webcache:
        container_name: webcache-server
        image: docker.io/alvidir/webcache:1.0.0
        restart: always
        volumes:
            - ./volume/webcache:/etc/webcache:ro
        security_opt:
            label: disable
        depends_on:
            - redis
        env_file:
            - .env