services:
    global-ingress:
        container_name: global-ingress
        image: docker.io/nginx:alpine
        restart: always
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./volumes/nginx:/etc/nginx:ro
            - logs:/etc/logs
        security_opt:
            label: disable
        networks:
            - shared

networks:
    shared:
        external: true

volumes:
    logs: