services:
    envoy:
        container_name: rauth-envoy
        image: docker.io/alvidir/envoy:0.0.1
        restart: always
        volumes:
            - ./volume/envoy:/etc/envoy/.config:ro
        security_opt:
            label: disable
        env_file:
            - .env

    nginx:
        container_name: rauth-nginx
        build: ./container/nginx
        restart: always
        volumes:
            - ./volume/nginx:/opt/bitnami/openresty/nginx/conf/server_blocks:ro
            - ./volume/lua:/etc/lua:ro
        security_opt:
            label: disable
        depends_on:
            - envoy
        networks:
            - shared
        env_file:
            - .env
    
    postgres:
        container_name: rauth-postgres
        image: docker.io/postgres:alpine3.17
        restart: on-failure
        volumes:
            - ./volume/postgres/dbdata:/data/postgres
            - ./volume/postgres/initdb:/docker-entrypoint-initdb.d
        security_opt:
            label: disable
        env_file:
            - .env
            
    redis:
        container_name: rauth-redis
        image: docker.io/redis:alpine3.17
        restart: always
        volumes:
            - ./volume/redis:/usr/local/etc/redis:ro
        security_opt:
            label: disable
        command: "redis-server /usr/local/etc/redis/redis.conf"

    rauth:
        container_name: rauth-server
        image: docker.io/alvidir/rauth:0.0.8
        restart: always
        volumes:
            - ./volume/rauth/templates:/etc/rauth/smtp/templates:ro
        security_opt:
            label: disable
        depends_on: 
            - postgres
            - redis
        env_file:
            - .env

    rauth-ui:
        container_name: rauth-ui
        image: docker.io/alvidir/rauth-ui:0.0.7
        restart: always
        security_opt:
            label: disable
        env_file:
            - .env

networks:
    shared:
        external: true

volumes:
    dbdata: