services:
    envoy:
        container_name: rauth-envoy
        build:
            context: ../envoy
            dockerfile: ./container/envoy/containerfile
        restart: always
        volumes:
            - ./volume/envoy:/etc/envoy/.config:ro
        security_opt:
            label: disable
        env_file:
            - .env

    nginx:
        container_name: rauth-nginx
        image: docker.io/nginx:1.23.2-alpine
        restart: always
        volumes:
            - ./volume/nginx:/etc/nginx/conf.d:ro
        security_opt:
            label: disable
        depends_on:
            - envoy
        networks:
            - shared
        env_file:
            - .env
    
    postgres:
        container_name: rauth-postgres
        image: docker.io/postgres:alpine3.17
        restart: on-failure
        volumes:
            - ./volume/postgres/dbdata:/data/postgres
            - ./volume/postgres/initdb:/docker-entrypoint-initdb.d
        security_opt:
            label: disable
        env_file:
            - .env
            
    redis:
        container_name: rauth-redis
        image: docker.io/redis:alpine3.17
        restart: always
        volumes:
            - ./volume/redis:/usr/local/etc/redis:ro
        security_opt:
            label: disable
        command: "redis-server /usr/local/etc/redis/redis.conf"

    grpc:
        container_name: rauth-grpc
        image: docker.io/alvidir/rauth:v0.0.10-grpc
        restart: always
        volumes:
            - ./volume/rauth/templates:/etc/rauth/smtp/templates:ro
        security_opt:
            label: disable
        depends_on: 
            - postgres
            - redis
        env_file:
            - .env
        environment:
            - SERVICE_PORT=${GRPC_SERVICE_PORT}

    rest:
        container_name: rauth-rest
        image: docker.io/alvidir/rauth:v0.0.10-rest
        restart: always
        security_opt:
            label: disable
        depends_on: 
            - redis
        env_file:
            - .env
        environment:
            - SERVICE_PORT=${REST_SERVICE_PORT}

    ui:
        container_name: rauth-ui
        image: docker.io/alvidir/rauth-ui:v0.0.8
        restart: always
        security_opt:
            label: disable
        env_file:
            - .env

networks:
    shared:
        external: true

volumes:
    dbdata: