name: Continuous delivery

on:
  release:
    types: published

  workflow_dispatch:

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: alvidir/filebrowser

jobs:
  push_server_to_registry:
    name: Push server image to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.event.release.tag_name }}
          containerfiles: |
            ./container/filebrowser/containerfile

      - name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

  push_worker_to_registry:
    name: Push worker image to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.event.release.tag_name }}-agent
          containerfiles: |
            ./container/agent/containerfile

      - name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
