name: Publish images

on:
  push:
    branches: [ main ]
    paths: [ ingress/container/nginx-lua ]

  workflow_dispatch:

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: alvidir/nginx-lua

jobs:
  push_nginx_lua_to_registry:
    name: Push nginx-lua image to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Get latest tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.1

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ steps.previoustag.outputs.tag }}
          containerfiles: |
            ./ingress/container/nginx-lua/containerfile

      - name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}